version: "3.9"
services:
  sh-images: 
    build: 
      context: .
      target: prod
    ports:
      - "4100:4100"
    environment:
      - NODE_ENV=production
    networks:
      - default
      - sh-network
    external_links:
      - hasura

networks:
  sh-network:
    external: true